/*
 * Generated by MTK DrvGen Version 10.01.0 for MT6261NP. Copyright MediaTek Inc. (C) 2012.
 * Sun Sep 22 13:55:06 2019
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*   Maui_Software
*
* Description:
* ------------
*  
*
* Author:
* -------
*  dongming.li       Generated By DRV TOOL
*
*============================================================================
****************************************************************************/
#ifdef __CUST_NEW__
#include "pmic_drv.h"
#include "dcl.h"


void pmu_drv_tool_customization_init(void)  
 {}  
 #endif /* __CUST_NEW__ */


